const B={
 sbi:{name:'SBI証券',url:'https://www.sbisec.co.jp/',tags:['NISA','投信','日本株','米国株','Vポイント'],p:{nisa:10,fund:10,domestic:10,foreign:10,card:9,points:9,small:9,beginner:8,app:9,fee:10,analysis:9,service:7},good:['NISAから日本株・米国株・投信まで幅広くまとめたい','三井住友カード・Vポイントを資産形成に使いたい','商品・取引手段の選択肢を広く持ちたい'],bad:['選択肢が多いため、初心者は最初に設定を整理すると使いやすい']},
 rakuten:{name:'楽天証券',url:'https://www.rakuten-sec.co.jp/',tags:['NISA','楽天カード','楽天ポイント','楽天経済圏','かぶミニ'],p:{nisa:10,fund:10,domestic:10,foreign:9,card:10,points:10,small:9,beginner:10,app:10,fee:10,analysis:8,service:8},good:['楽天カード・楽天ポイントを日常的に使っている','NISAの投信積立を楽天経済圏とまとめたい','初心者でも操作しやすい環境を重視する'],bad:['カードや対象商品によってポイント条件が異なるため最新条件の確認が必要']},
 monex:{name:'マネックス証券',url:'https://www.monex.co.jp/',tags:['NISA','dカード','dポイント','米国株','投信保有ポイント'],p:{nisa:10,fund:10,domestic:9,foreign:10,card:9,points:9,small:10,beginner:8,app:9,fee:10,analysis:10,service:8},good:['米国株など海外株も重視したい','dカード・dポイントを活用したい','投信保有ポイントや1株投資も評価したい'],bad:['カード・ポイント条件は利用額や商品等で変わる場合がある']},
 mufg:{name:'三菱UFJ eスマート証券',url:'https://kabu.com/',tags:['NISA','三菱UFJカード','au PAY','Ponta','プチ株'],p:{nisa:9,fund:9,domestic:10,foreign:8,card:10,points:10,small:10,beginner:8,app:8,fee:10,analysis:8,service:8},good:['三菱UFJカード・au PAYカード・Pontaを活用したい','日本株を少額から始めたい','MUFG・au系サービスとの連携を重視する'],bad:['カード・ポイント還元はカード種別や条件によって変動する']},
 matsui:{name:'松井証券',url:'https://www.matsui.co.jp/',tags:['NISA','JCB','J-POINT','初心者向け','投信'],p:{nisa:9,fund:10,domestic:9,foreign:8,card:9,points:9,small:8,beginner:10,app:10,fee:10,analysis:8,service:10},good:['投資初心者で分かりやすさ・サポートを重視する','JCB・J-POINTを活用したい','投信の長期保有を中心に考えている'],bad:['商品・ポイント条件は公式の最新情報を確認したい']},
 connect:{name:'大和コネクト証券',url:'https://www.connect-sec.co.jp/',tags:['NISA','スマホ','少額投資','大和証券グループ'],p:{nisa:8,fund:8,domestic:9,foreign:8,card:6,points:7,small:10,beginner:9,app:10,fee:9,analysis:7,service:8},good:['スマホ中心でシンプルに始めたい','少額投資を重視する','大和証券グループのサービスも意識したい'],bad:['総合ネット証券と比べて商品・機能の幅を重視する人は比較が必要']},
 paypay:{name:'PayPay証券',url:'https://www.paypay-sec.co.jp/',tags:['NISA','PayPay','100円投資','スマホ','米国株'],p:{nisa:8,fund:8,domestic:8,foreign:9,card:7,points:10,small:10,beginner:10,app:10,fee:8,analysis:6,service:8},good:['PayPayアプリ・PayPayポイントを普段から使う','100円単位など少額から始めたい','スマホ完結の分かりやすさを重視する'],bad:['本格的な銘柄分析や商品数を最優先する場合は他社も比較したい']},
 moomoo:{name:'moomoo証券',url:'https://www.moomoo.com/jp/',tags:['NISA','米国株','分析','高機能アプリ','日本株'],p:{nisa:8,fund:6,domestic:8,foreign:10,card:4,points:4,small:8,beginner:6,app:10,fee:9,analysis:10,service:6},good:['米国株・海外株や詳細な市場分析を重視する','高機能なスマホアプリを使いたい','チャート・銘柄分析を深く見たい'],bad:['初心者向けのシンプルさやポイント経済圏を最優先する人は他社も比較したい']},
 okasan:{name:'岡三オンライン',url:'https://www.okasan-online.co.jp/',tags:['NISA','日本株','投資情報','ネット証券'],p:{nisa:8,fund:8,domestic:9,foreign:6,card:4,points:4,small:7,beginner:7,app:8,fee:9,analysis:9,service:8},good:['日本株と投資情報を重視したい','NISA・投信も使いつつ国内株を研究したい','情報提供や分析環境を評価したい'],bad:['カード・ポイント経済圏を中心に選びたい場合は他社も比較したい']},
 gmo:{name:'GMOクリック証券',url:'https://www.click-sec.com/',tags:['NISA','日本株','FX','取引ツール','低コスト'],p:{nisa:8,fund:6,domestic:9,foreign:7,card:3,points:3,small:7,beginner:7,app:9,fee:10,analysis:10,service:7},good:['取引ツールやコストを重視する','日本株の売買・分析を積極的に行いたい','GMO系サービスとの連携を意識する'],bad:['NISAの投信積立やカード・ポイントを最優先する人は他社も比較したい']},
 dmm:{name:'DMM株',url:'https://kabu.dmm.com/',tags:['NISA','日本株','米国株','取引ツール','低コスト'],p:{nisa:8,fund:5,domestic:9,foreign:8,card:3,points:3,small:7,beginner:7,app:9,fee:10,analysis:9,service:7},good:['日本株・米国株の売買コストを重視する','シンプルな取引環境を使いたい','NISAで株式を中心に取引したい'],bad:['投信積立やカード・ポイントを中心に資産形成したい人は他社も比較したい']},
 nomura:{name:'野村證券',url:'https://www.nomura.co.jp/',tags:['NISA','総合証券','相談','商品選択','店舗'],p:{nisa:10,fund:9,domestic:9,foreign:8,card:3,points:3,small:5,beginner:8,app:7,fee:6,analysis:9,service:10},good:['対面相談や総合的な金融サービスを重視する','大手証券の情報・サポートを活用したい','NISAを含め幅広い資産運用を相談したい'],bad:['ネット証券の低コスト・スマホ完結を最優先する人は比較が必要']},
 daiwa:{name:'大和証券',url:'https://www.daiwa.jp/',tags:['NISA','総合証券','相談','投信','店舗'],p:{nisa:10,fund:9,domestic:9,foreign:8,card:3,points:3,small:5,beginner:8,app:7,fee:6,analysis:9,service:10},good:['対面相談とオンラインを併用したい','大手証券のサポート・情報力を重視する','NISAを含む資産運用を長期で相談したい'],bad:['手数料の低さやスマホ特化を最優先する場合はネット証券も比較したい']},
 smbc:{name:'SMBC日興証券',url:'https://www.smbcnikko.co.jp/',tags:['NISA','総合証券','dポイント','IPO','相談'],p:{nisa:10,fund:9,domestic:9,foreign:8,card:4,points:6,small:5,beginner:8,app:8,fee:6,analysis:9,service:10},good:['大手証券の情報・サポートを重視する','dポイントなど金融サービスとの連携を評価する','NISA以外も含めて総合的に相談したい'],bad:['低コスト・完全スマホ完結を最優先する場合はネット証券も比較したい']},
 iwai:{name:'岩井コスモ証券',url:'https://www.iwaicosmo.co.jp/',tags:['NISA','日本株','投信','対面・ネット'],p:{nisa:9,fund:8,domestic:9,foreign:7,card:3,points:3,small:7,beginner:8,app:7,fee:8,analysis:8,service:9},good:['日本株を中心にNISAも使いたい','ネットと相談サービスの両方を検討したい','国内株の取引環境を重視する'],bad:['カード・ポイント経済圏を最優先する場合はネット証券も比較したい']}
};
const Q=[
['投資目的','最も近い投資目的は？',[['老後など長期の資産形成',{nisa:4,fund:4,beginner:2}],['配当・株主優待',{domestic:5,small:2}],['日本株を積極的に売買',{domestic:6,analysis:3}],['米国株など海外株',{foreign:7}],['まだ決めていない',{beginner:5,nisa:2}]],'s'],
['経験','投資経験は？',[['ほぼない',{beginner:6,service:2,app:2}],['1年未満',{beginner:4,app:2}],['1〜3年',{app:2,analysis:2}],['3年以上',{analysis:4,domestic:2,foreign:2}]],'s'],
['NISA','NISAでは何を中心に？',[['投資信託の積立',{nisa:5,fund:6}],['日本株',{nisa:5,domestic:6}],['米国株・海外株',{nisa:5,foreign:6}],['投資信託＋株を両方',{nisa:5,fund:3,domestic:3,foreign:3}],['未定',{nisa:3,beginner:3}]],'s'],
['投資額','毎月の投資予定額は？',[['〜1万円',{small:5,beginner:3}],['1〜5万円',{fund:4,nisa:3}],['5〜10万円',{fund:5,nisa:4,card:2}],['10万円以上',{fund:5,nisa:5,fee:2}]],'s'],
['カード','普段よく使うカード・経済圏は？',[['三井住友カード／Olive',{card:7,points:5}],['楽天カード',{card:7,points:5}],['dカード',{card:7,points:5}],['JCB',{card:6,points:4}],['au PAYカード／三菱UFJカード',{card:7,points:5}],['PayPay',{card:5,points:6}],['特にない',{fee:2}]],'s'],
['ポイント','重視するポイントは？（複数選択）',[['Vポイント',{points:6}],['楽天ポイント',{points:6}],['dポイント',{points:6}],['Ponta',{points:6}],['J-POINT',{points:5}],['PayPayポイント',{points:6}],['ポイントは重視しない',{fee:3}]],'m'],
['クレカ積立','クレカ積立への関心は？',[['ぜひ使いたい',{card:6,points:4}],['できれば使いたい',{card:4,points:2}],['どちらでもいい',{card:1}],['使わない',{fee:3}]],'s'],
['少額投資','1株・100円単位など少額から投資できることは？',[['非常に重要',{small:7}],['重要',{small:5}],['あまり重要でない',{small:1}],['必要ない',{fee:2}]],'s'],
['海外株','海外株への投資予定は？',[['積極的に',{foreign:7}],['将来的には',{foreign:4}],['少し興味がある',{foreign:2}],['日本株・投信だけ',{domestic:2,fund:2}]],'s'],
['投信','投資信託を長期保有する予定は？',[['中心にする',{fund:7,nisa:3}],['かなり使う',{fund:5}],['少し使う',{fund:2}],['ほとんど使わない',{domestic:2,foreign:2}]],'s'],
['投信ポイント','投信保有中のポイントを重視する？',[['かなり重視',{points:5,fund:5}],['少し重視',{points:2,fund:2}],['気にしない',{fund:2}]],'s'],
['手数料','手数料の低さは？',[['最優先',{fee:8}],['かなり重視',{fee:6}],['普通',{fee:2}],['サポートや特典を優先',{service:3,beginner:2}]],'s'],
['アプリ','スマホアプリの分かりやすさは？',[['最優先',{app:8,beginner:3}],['重視',{app:5,beginner:2}],['普通',{app:2}],['気にしない',{}]],'s'],
['分析','チャート・分析機能をどの程度使いたい？',[['シンプルで十分',{beginner:4,app:3}],['基本機能で十分',{app:2}],['詳しい分析を使いたい',{analysis:7,app:4}],['かなり本格的に使いたい',{analysis:9,app:5}]],'s'],
['取引頻度','日本株の取引頻度は？',[['ほぼ積立',{fund:3,nisa:3,beginner:2}],['月に数回',{domestic:3,app:2}],['週に数回',{domestic:5,app:4}],['頻繁に売買',{domestic:6,app:5,analysis:3}]],'s'],
['情報','投資情報・レポートは？',[['あまり必要ない',{fee:2}],['基本情報があれば十分',{app:2}],['詳しい情報がほしい',{analysis:5,service:3}],['専門家の情報も重視',{analysis:6,service:5}]],'s'],
['相談','人に相談できることは？',[['かなり重要',{service:8}],['できればほしい',{service:5}],['不要',{app:2,fee:2}]],'s'],
['店舗','店舗・対面サービスは？',[['ぜひ使いたい',{service:8}],['必要なら使いたい',{service:5}],['ネットだけでよい',{app:3,fee:2}]],'s'],
['IPO','IPOなど新規公開株への関心は？',[['積極的に狙いたい',{analysis:3,service:3}],['少し興味がある',{analysis:2}],['特にない',{}]],'s'],
['米国株','米国株で重視することは？',[['銘柄数・分析機能',{foreign:6,analysis:5}],['低コスト',{foreign:5,fee:5}],['少額・分かりやすさ',{foreign:4,small:3,beginner:3}],['興味なし',{domestic:2}]],'s'],
['日本株','日本株で重視することは？',[['売買コスト',{domestic:5,fee:5}],['分析・取引ツール',{domestic:5,analysis:5,app:3}],['1株など少額投資',{domestic:4,small:6}],['配当・優待を長期保有',{domestic:5,fund:2}]],'s'],
['銀行連携','銀行との連携は？',[['特に重視しない',{fee:2}],['楽天銀行など楽天系',{points:4}],['三井住友銀行などSMBC系',{points:3,service:2}],['三菱UFJ銀行・au系',{points:4}],['PayPay銀行・PayPay系',{points:5}],['大和・大手証券系',{service:4}]],'s'],
['ポイント還元','投資でポイントが貯まることは？',[['かなり重要',{points:7}],['少し重要',{points:4}],['どちらでもいい',{points:1}],['不要',{fee:2}]],'s'],
['積立','自動積立を中心にしたい？',[['ほぼ完全自動で運用したい',{fund:5,beginner:4,nisa:3}],['自動積立＋時々売買',{fund:4,nisa:3,app:2}],['自分で売買したい',{domestic:4,analysis:3}],['まだ分からない',{beginner:3}]],'s'],
['商品数','投資商品の選択肢は？',[['できるだけ多い方がいい',{fund:5,foreign:4}],['十分な種類があればよい',{fund:3,foreign:2}],['少数で分かりやすい方がいい',{beginner:4,app:3}],['株中心なので気にしない',{domestic:3}]],'s'],
['UI','画面の情報量は？',[['シンプルがいい',{beginner:5,app:4}],['普通がいい',{app:2}],['情報量が多い方がいい',{analysis:6,app:3}]],'s'],
['サポート','困ったときのサポートは？',[['手厚さ最優先',{service:8,beginner:3}],['標準でよい',{service:3}],['自分で調べるので不要',{fee:2,analysis:2}]],'s'],
['長期','10年以上の長期運用を想定？',[['はい',{nisa:5,fund:5,beginner:2}],['たぶんはい',{nisa:4,fund:3}],['短期売買もしたい',{domestic:4,foreign:3,analysis:4}],['分からない',{beginner:2}]],'s'],
['方針','最後に最も近い考え方は？',[['カード・ポイントを最大化',{card:5,points:7}],['NISAを長期でシンプルに',{nisa:6,fund:6}],['日本株を研究したい',{domestic:7,analysis:5}],['海外株も幅広く',{foreign:7,analysis:4}],['初心者なので分かりやすさ',{beginner:8,app:5}],['専門家に相談しながら進めたい',{service:8,beginner:3}]],'s']
];
let i=0,A=[],$=x=>document.getElementById(x);
function reset(){i=0;A=[]}
function render(){const q=Q[i],s=A[i]||[];$('no').textContent=i+1;$('total').textContent=Q.length;$('cat').textContent=q[0];$('question').textContent=q[1];$('hint').textContent=q[3]=='m'?'複数選択できます。選択後に「次へ」を押してください。':'回答すると自動で次へ進みます。';$('bar').style.width=(i+1)/Q.length*100+'%';$('answers').innerHTML=q[2].map((x,n)=>`<button class="answer ${s.includes(n)?'selected':''}" data-i="${n}"><strong>${x[0]}</strong></button>`).join('');$('next').classList.toggle('hidden',q[3]!='m');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const n=+b.dataset.i;if(q[3]=='m'){let a=A[i]||[];const none=q[2].length-1;if(n===none)a=[none];else a=a.filter(x=>x!==none),a=a.includes(n)?a.filter(x=>x!==n):[...a,n];A[i]=a;render()}else{A[i]=[n];i<Q.length-1?(i++,render()):show()}})}
$('next').onclick=()=>{if(!(A[i]||[]).length)return;i<Q.length-1?(i++,render()):show()};
function rawScore(key){let total=0;A.forEach((arr,qi)=>arr.forEach(n=>Object.entries(Q[qi][2][n][1]).forEach(([d,w])=>{total+=w*(B[key].p[d]||0)/10})));return total}
// 公平性キャリブレーション：中立回答を多数シミュレーションし、15社の期待推薦確率が1/15になるよう切片を調整。
// betaは推薦確率の鋭さ。切片は固定値なので、利用者ごとに有利な会社が変わることはない。
const FAIR_BETA=0.15;
const FAIR_BIAS={sbi:-3.001810,rakuten:-4.173759,monex:-3.416825,mufg:-2.396359,matsui:-3.335495,connect:-0.107660,paypay:-1.278544,moomoo:2.241121,okasan:2.474329,gmo:2.748662,dmm:3.134579,nomura:1.925722,daiwa:1.925722,smbc:0.562450,iwai:2.697865};
function calibratedValues(){const o={};Object.keys(B).forEach(k=>o[k]=rawScore(k)+FAIR_BIAS[k]);return o}
function scores(){const v=calibratedValues(),ks=Object.keys(v),m=Math.max(...ks.map(k=>FAIR_BETA*v[k])),e={};let sum=0;ks.forEach(k=>{e[k]=Math.exp(FAIR_BETA*v[k]-m);sum+=e[k]});ks.forEach(k=>e[k]=e[k]/sum*100);return e}
function profile(){const dims={nisa:0,fund:0,domestic:0,foreign:0,card:0,points:0,small:0,beginner:0,app:0,fee:0,analysis:0,service:0};A.forEach((arr,qi)=>arr.forEach(n=>Object.entries(Q[qi][2][n][1]).forEach(([d,w])=>dims[d]+=w)));return dims}
function show(){const s=scores(),r=Object.entries(s).sort((a,b)=>b[1]-a[1]),mx=Math.max(...r.map(x=>x[1]),1),top=B[r[0][0]],p=profile();$('summary').textContent=`回答内容からは「${top.name}」の適合度が最も高い結果です。全${Object.keys(B).length}社を同じ中立条件から比較し、各社の基礎性能による構造的な有利・不利を統計的に補正しています。表示値は公平補正後の推薦確率で、15社の合計が100%になるよう正規化しています。`;$('profile').innerHTML=[['長期・NISA',p.nisa+p.fund],['日本株',p.domestic],['海外株',p.foreign],['カード・ポイント',p.card+p.points],['少額投資',p.small],['初心者・操作性',p.beginner+p.app],['分析・取引',p.analysis],['相談・サポート',p.service]].map(x=>`<div><b>${x[0]}</b><span>${x[1]} pt</span></div>`).join('');$('ranking').innerHTML=r.map(([k,v],n)=>{const b=B[k];return `<article class="rank ${n==0?'top':''}"><div class="rankhead"><span>${n+1}位　${b.name}</span><span class="score">${v.toFixed(1)}%</span></div><div class="barbg"><div class="barfill" style="width:${Math.max(8,v/mx*100)}%"></div></div><div class="tags">${b.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div><span class="metric">NISA・投信 ${b.p.nisa+b.p.fund}/20</span><span class="metric">日本株・少額 ${b.p.domestic+b.p.small}/20</span><span class="metric">カード・ポイント ${b.p.card+b.p.points}/20</span><span class="metric">分析・操作 ${b.p.analysis+b.p.app}/20</span></div><h4>向いている理由</h4><ul>${b.good.map(x=>`<li class="reason">${x}</li>`).join('')}</ul><h4>注意点</h4><ul>${b.bad.map(x=>`<li class="reason">${x}</li>`).join('')}</ul><a class="official" href="${b.url}" target="_blank" rel="noopener">公式サイトで最新条件を確認 →</a></article>`}).join('');$('quiz').classList.add('hidden');$('result').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
$('startBtn').onclick=()=>{reset();$('start').classList.add('hidden');$('result').classList.add('hidden');$('quiz').classList.remove('hidden');render()};$('retry').onclick=()=>{reset();$('result').classList.add('hidden');$('quiz').classList.remove('hidden');render();scrollTo({top:0,behavior:'smooth'})};
