const B={sbi:{name:'SBI証券',url:'https://www.sbisec.co.jp/',tags:['三井住友カード','Vポイント','NISA','日本株','S株'],p:{nisa:9,fund:9,domestic:9,foreign:9,card:9,points:8,small:8,beginner:7,app:8,fee:9},good:['NISA・投信・日本株・海外株を幅広く使いたい','三井住友カード／Olive・Vポイントを活用したい','少額の日本株取引も試したい'],bad:['カード種類や年間利用額等でクレカ積立条件が変わる']},rakuten:{name:'楽天証券',url:'https://www.rakuten-sec.co.jp/',tags:['楽天カード','楽天ポイント','楽天経済圏','NISA','かぶミニ'],p:{nisa:9,fund:9,domestic:9,foreign:9,card:10,points:10,small:8,beginner:9,app:9,fee:9},good:['楽天カード・楽天ポイントを普段から使う','楽天経済圏とNISAの投信積立をまとめたい','初心者向けの使いやすさを重視する'],bad:['カード種類・対象ファンド等でポイント進呈率が変わる']},monex:{name:'マネックス証券',url:'https://www.monex.co.jp/',tags:['dカード','dポイント','NISA','ワン株','投信保有ポイント'],p:{nisa:9,fund:9,domestic:8,foreign:9,card:9,points:9,small:9,beginner:7,app:8,fee:9},good:['dカード・dポイントを資産形成にも活用したい','海外株も重視する','1株投資や投信保有ポイントを評価する'],bad:['dカード積立の還元率はカード・入会年数・積立額等で変わる']},au:{name:'三菱UFJ eスマート証券',url:'https://kabu.com/',tags:['三菱UFJカード','au PAYカード','Ponta','NISA','プチ株'],p:{nisa:8,fund:8,domestic:9,foreign:7,card:9,points:9,small:9,beginner:7,app:7,fee:9},good:['三菱UFJカード・au PAYカード・Pontaを活用したい','日本株を少額から始めたい','au／三菱UFJ系サービスとの連携を重視する'],bad:['カードによる積立条件や還元内容を確認する必要がある']},matsui:{name:'松井証券',url:'https://www.matsui.co.jp/',tags:['JCB','J-POINT','NISA','投信残高ポイント','初心者向け'],p:{nisa:8,fund:9,domestic:8,foreign:7,card:8,points:8,small:7,beginner:9,app:9,fee:9},good:['投資初心者で分かりやすさを重視する','JCB・J-POINTを活用したい','投信の長期保有を重視する'],bad:['カード積立の対象カード・条件は公式情報で確認する']}},
Q=[
['投資目的','最も近い投資目的は？',[['老後など長期資産形成',{nisa:4,fund:3,beginner:2}],['配当・株主優待',{domestic:5,small:2}],['日本株を積極的に売買',{domestic:5,app:2}],['米国株など海外株',{foreign:6}],['まだ決めていない',{beginner:4,nisa:2}]],'s'],
['投資経験','投資経験は？',[['ほぼない',{beginner:5,app:3}],['1年未満',{beginner:3}],['1〜3年',{app:2}],['3年以上',{app:3,foreign:1,domestic:1}]],'s'],
['NISA','NISAでは何を中心に？',[['投資信託の積立',{nisa:4,fund:5}],['日本株',{nisa:4,domestic:5}],['米国株・海外株',{nisa:4,foreign:5}],['未定',{nisa:3,beginner:3}]],'s'],
['投資額','毎月の積立予定額は？',[['〜1万円',{small:4,beginner:2}],['1〜5万円',{fund:4,nisa:3}],['5〜10万円',{fund:5,nisa:4,card:2}],['10万円以上',{fund:5,nisa:5,fee:2}]],'s'],
['カード','よく使うカードは？',[['三井住友カード／Olive',{card:7,points:5}],['楽天カード',{card:7,points:5}],['dカード',{card:7,points:5}],['JCBオリジナルシリーズ',{card:6,points:4}],['au PAYカード／三菱UFJカード',{card:7,points:5}],['特にない',{fee:2}]],'s'],
['ポイント','重視するポイントは？（複数選択）',[['Vポイント',{points:5}],['楽天ポイント',{points:5}],['dポイント',{points:5}],['Ponta',{points:5}],['J-POINT',{points:4}],['ポイントは重視しない',{fee:3}]],'m'],
['クレカ積立','クレカ積立への関心は？',[['ぜひ使いたい',{card:5,points:4}],['できれば使いたい',{card:3,points:2}],['どちらでもいい',{card:1}],['使わない',{fee:3}]],'s'],
['日本株','1株など少額で日本株を買えることは？',[['非常に重要',{small:7,domestic:4}],['重要',{small:5,domestic:2}],['あまり重要でない',{small:1}],['必要ない',{fee:2}]],'s'],
['海外株','海外株への投資予定は？',[['積極的に',{foreign:7}],['将来的には',{foreign:4}],['少し興味',{foreign:2}],['日本株・投信だけ',{domestic:2,fund:2}]],'s'],
['投信ポイント','投信保有中のポイントを重視？',[['かなり重視',{points:4,fund:5}],['少し重視',{points:2,fund:2}],['気にしない',{fund:2}]],'s'],
['手数料','手数料の低さは？',[['最優先',{fee:7}],['かなり重視',{fee:5}],['普通',{fee:2}],['使いやすさ・特典優先',{beginner:2,app:2,points:2}]],'s'],
['アプリ','スマホアプリの分かりやすさは？',[['最優先',{app:7,beginner:3}],['重視',{app:5,beginner:2}],['普通',{app:2}],['気にしない',{}]],'s'],
['取引頻度','日本株の取引頻度は？',[['ほぼ積立',{fund:3,nisa:3,beginner:2}],['月に数回',{domestic:3,app:2}],['週に数回',{domestic:5,app:4}],['頻繁に売買',{domestic:6,app:5}]],'s'],
['分析機能','チャート・分析機能をどの程度使いたい？',[['シンプルさ優先',{beginner:5,app:3}],['基本機能で十分',{app:2}],['詳しい分析も使いたい',{app:5,domestic:3,foreign:2}]],'s'],
['総合方針','最後に最も近い考え方は？',[['カード・ポイントを最大化',{card:4,points:6}],['NISAを長期でシンプルに',{nisa:5,fund:5}],['日本株を研究したい',{domestic:6,app:4}],['海外株も幅広く',{foreign:6,app:3}],['初心者なので分かりやすさ',{beginner:7,app:5}]],'s']];
let i=0,A=[],$=x=>document.getElementById(x);function reset(){i=0;A=[]}function render(){let q=Q[i],s=A[i]||[];$('no').textContent=i+1;$('total').textContent=Q.length;$('cat').textContent=q[0];$('question').textContent=q[1];$('hint').textContent=q[3]=='m'?'複数選択できます。':'回答すると自動で次へ進みます。';$('bar').style.width=(i+1)/Q.length*100+'%';$('answers').innerHTML=q[2].map((x,n)=>`<button class="answer ${s.includes(n)?'selected':''}" data-i="${n}"><strong>${x[0]}</strong></button>`).join('');$('next').classList.toggle('hidden',q[3]!='m');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{let n=+b.dataset.i;if(q[3]=='m'){let a=A[i]||[];a=n==q[2].length-1?[n]:[...a.filter(x=>x!==q[2].length-1)];if(n!=q[2].length-1)a=a.includes(n)?a.filter(x=>x!==n):[...a,n];A[i]=a;render()}else{A[i]=[n];i<Q.length-1?(i++,render()):show()}})}$('next').onclick=()=>{if(!(A[i]||[]).length)return;i<Q.length-1?(i++,render()):show()};
function rawScore(key){let total=0;A.forEach((arr,qi)=>arr.forEach(n=>Object.entries(Q[qi][2][n][1]).forEach(([d,w])=>{total+=w*(B[key].p[d]||0)/10})));return total}
function expectedScore(key){let total=0,count=0;Q.forEach(q=>q[2].forEach(a=>{let s=0;Object.entries(a[1]).forEach(([d,w])=>s+=w*(B[key].p[d]||0)/10);total+=s;count++}));return count?total/count:0}
/* Fairness calibration: subtract each company's expected score over the full answer universe.
   This gives every broker the same neutral prior and prevents a company with
   broadly high raw feature scores from winning regardless of the user's answers. */
function scores(){let o={};Object.keys(B).forEach(k=>o[k]=rawScore(k)-expectedScore(k)*Q.length);return o}function show(){let s=scores(),r=Object.entries(s).sort((a,b)=>b[1]-a[1]),mx=Math.max(...r.map(x=>x[1]),1),top=B[r[0][0]];$('summary').textContent=`回答内容からは「${top.name}」との適合度が最も高い結果です。上位3社を比較してください。各社の基礎点による有利・不利を補正し、同じ事前条件から比較しています。`;$('profile').innerHTML=['投資信託・積立','日本株','海外株','カード','ポイント','初心者適性'].map(x=>`<div><b>${x}</b><span>回答をスコアに反映</span></div>`).join('');$('ranking').innerHTML=r.map(([k,v],n)=>{let b=B[k];return `<article class="rank ${n==0?'top':''}"><div class="rankhead"><span>${n+1}位　${b.name}</span><span class="score">${v.toFixed(1)} pt</span></div><div class="barbg"><div class="barfill" style="width:${Math.max(8,v/mx*100)}%"></div></div><div class="tags">${b.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div><span class="metric">NISA・投信 ${b.p.nisa+b.p.fund}/20</span><span class="metric">日本株・少額 ${b.p.domestic+b.p.small}/20</span><span class="metric">カード・ポイント ${b.p.card+b.p.points}/20</span></div><h4>向いている理由</h4><ul>${b.good.map(x=>`<li class="reason">${x}</li>`).join('')}</ul><h4>注意点</h4><ul>${b.bad.map(x=>`<li class="reason">${x}</li>`).join('')}</ul><a class="official" href="${b.url}" target="_blank" rel="noopener">公式サイトで最新条件を確認 →</a></article>`}).join('');$('quiz').classList.add('hidden');$('result').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}$('startBtn').onclick=()=>{reset();$('start').classList.add('hidden');$('result').classList.add('hidden');$('quiz').classList.remove('hidden');render()};$('retry').onclick=()=>{reset();$('result').classList.add('hidden');$('quiz').classList.remove('hidden');render();scrollTo({top:0,behavior:'smooth'})};
